### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by FalcoGer** [raspberrypi-ui/pi-greeter#3]
I'm running an raspberri pi with raspbian gnu/linux 9 (stretch). as a tool to log some data that comes over the network. It comes with pi-greeter. I want the ui installed because some people sometimes want to have a look at it and are not familiar with linux, connecting with xrdp.
so pi-greeter runs most of the time when nobody is looking.
And after letting it run for a while I noticed this:

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
26727 root      20   0   94788  57128  21384 S   0.3  6.0   3:10.85 Main
21922 lightdm   20   0  113744  41700  19176 S   0.3  4.4 222:04.26 pi-greeter
21899 root      20   0  133924  32488  23256 S   0.7  3.4 277:50.45 Xorg
[...]
```

Main is the logging program the pi is there for, running on mono. It runs as root because it's set up as a service.
I think 40MB for a simple login window is a bit much, yes?

Since the raspberry is so limited in memory, this is a real issue, since I want to install a database service as well. And that'd use up quite a bit.

I wish I could tell you the version, but well...
```
pi@raspberrypi:~ $ pi-greeter --help

(pi-greeter:1692): Gtk-WARNING **: cannot open display:
pi@raspberrypi:~ $ pi-greeter -v

(pi-greeter:1694): Gtk-WARNING **: cannot open display:
pi@raspberrypi:~ $ pi-greeter -V

(pi-greeter:1696): Gtk-WARNING **: cannot open display:
pi@raspberrypi:~ $ pi-greeter --version

(pi-greeter:1698): Gtk-WARNING **: cannot open display:
pi@raspberrypi:~ $ pi-greeter -h

(pi-greeter:1700): Gtk-WARNING **: cannot open display:
pi@raspberrypi:~ $ pi-greeter -?

(pi-greeter:1702): Gtk-WARNING **: cannot open display:
pi@raspberrypi:~ $ man pi-greeter
No manual entry for pi-greeter
See 'man 7 undocumented' for help when manual pages are not available.
```

**Comment by spl237** [comment]
pi-greeter is actually just a heavily cut-down version of the standard LightDM GTK greeter; all I did was to modify the code which displays the background picture and cut out a lot of other features, such as the menu. 

It's very likely, therefore, that whatever problem is causing this memory consumption was in the original LightDM GTK greeter - I suggest you try running that instead and see if it makes any difference. If it turns out that the LightDM GTK greeter is not hogging memory in the same way, I'll investigate whether my changes have caused a problem.

**Comment by FalcoGer** [comment]
How would I go about changing it out?
Are there perhaps alternatives?

**Comment by spl237** [comment]
Update the greeter-session line in /etc/lightdm/lightdm.conf - change it from pi-greeter to lightdm-gtk-greeter.conf.
